CREATE TABLE IF NOT EXISTS USERS(
    user_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE,
    country VARCHAR(2) DEFAULT NULL,
    account_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_active_at TIMESTAMP DEFAULT NULL,
    password VARCHAR(200) NOT NULL
);




