/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ChessBoard`; params?: Router.UnknownInputParams; } | { pathname: `/engine`; params?: Router.UnknownInputParams; } | { pathname: `/game`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/play`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/style`; params?: Router.UnknownInputParams; } | { pathname: `/type`; params?: Router.UnknownInputParams; } | { pathname: `/selfPlay`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/ChessBoard`; params?: Router.UnknownOutputParams; } | { pathname: `/engine`; params?: Router.UnknownOutputParams; } | { pathname: `/game`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/play`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/style`; params?: Router.UnknownOutputParams; } | { pathname: `/type`; params?: Router.UnknownOutputParams; } | { pathname: `/selfPlay`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/ChessBoard${`?${string}` | `#${string}` | ''}` | `/engine${`?${string}` | `#${string}` | ''}` | `/game${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/play${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/style${`?${string}` | `#${string}` | ''}` | `/type${`?${string}` | `#${string}` | ''}` | `/selfPlay${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ChessBoard`; params?: Router.UnknownInputParams; } | { pathname: `/engine`; params?: Router.UnknownInputParams; } | { pathname: `/game`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/play`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/style`; params?: Router.UnknownInputParams; } | { pathname: `/type`; params?: Router.UnknownInputParams; } | { pathname: `/selfPlay`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
